###
POST http://localhost:8080/api/wells
Content-Type: application/json

{
  "name": "Well Xeta",
  "latitude": 26.5,
  "longitude": 52.3
}

###
POST http://localhost:8080/api/wells/delete?id=74b0cf21-c7e6-4969-9015-11be26113293

###
DELETE http://localhost:8080/api/wells/c123d040-add3-456f-bea4-9904174dea8f

###
GET http://localhost:8080/api/wells

###
POST http://localhost:8080/api/wells/3d99d47e-e4c5-4a86-9e94-3ef6034be2cb/timeseries
Content-Type: application/json

{"timestamp":1713891600000,"pressure":100,"oilRate":55,"temperature":85}

###
POST http://localhost:8080/api/wells/56322a37-33ce-4f9a-8674-41f123c5d3b6/timeseries/batch
Content-Type: application/json

[{"timestamp":1713891600000,"pressure":100,"oilRate":55,"temperature":85}, {"timestamp":1713891700000,"pressure":120,"oilRate":45,"temperature":65}]

###
GET http://localhost:8080/api/wells/3d99d47e-e4c5-4a86-9e94-3ef6034be2cb/timeseries?from=1713880000000&to=1713900000000
